services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: devboard-app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=dbuser
      - DB_PASSWORD=dbpassword
      - DB_NAME=programming_channel_db
      - PORT=3000
      - SESSION_SECRET=docker_session_secret
      - ADMIN_PASSWORD=admin_password
    volumes:
      - ./server/uploads:/app/server/uploads
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: devboard-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=programming_channel_db
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpassword
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data: